(function(){
'use strict';
const colors=['#0b506b','#19a99d','#a9d650','#e1a146','#6e78a5','#3b8bb0'];
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const niceMax=value=>{if(value<=0)return 10;const p=Math.pow(10,Math.floor(Math.log10(value))),n=value/p;return (n<=2?2:n<=5?5:10)*p};
const fmt=value=>{const n=Number(value);if(!Number.isFinite(n))return String(value??'');return n>=1000?Math.round(n).toLocaleString('en-IN'):n>=100?Math.round(n).toString():n.toFixed(n<10?2:1).replace(/\.0$/,'')};
function createScale(values,multiplier=1.06){const clean=values.map(Number).filter(Number.isFinite).map(v=>Math.max(0,v)),positive=clean.filter(v=>v>0),rawMax=Math.max(1,...clean),rawMin=Math.min(...positive),max=niceMax(rawMax*multiplier),ratio=positive.length>1?rawMax/rawMin:1,adaptive=ratio>=25;return{max,adaptive,ratio,project:v=>{const n=Math.max(0,Number(v)||0)/max;return adaptive?Math.sqrt(n):n},tick:t=>max*Math.pow(Math.max(0,1-t),adaptive?2:1),pixels:(v,size,min=4)=>{const n=Math.max(0,Number(v)||0);return n>0?Math.max(min,(adaptive?Math.sqrt(n/max):n/max)*size):0}}}
window.AdaptiveChartScale={create:createScale};
function scaleNote(scale,W){return scale.adaptive?'<text class="adaptive-scale-label" x="'+(W-28)+'" y="18" text-anchor="end">Adaptive visibility scale · exact values on hover</text>':''}
function grid(scale,W=1000,H=350,p=60){return [0,1,2,3,4].map(i=>{const y=p+i*(H-2*p)/4,v=scale.tick(i/4);return '<line x1="'+p+'" y1="'+y+'" x2="'+(W-25)+'" y2="'+y+'"/><text class="axis-label" x="'+(p-10)+'" y="'+(y+4)+'" text-anchor="end">'+fmt(v)+'</text>'}).join('')}
function line(labels,series){const W=1000,H=350,p=60,all=series.flatMap(s=>s.values),scale=createScale(all,1.05),span=Math.max(1,labels.length-1);return '<svg viewBox="0 0 '+W+' '+H+'" aria-label="Line chart">'+scaleNote(scale,W)+'<g class="analytics-gridlines">'+grid(scale,W,H,p)+'</g>'+series.map((s,j)=>{const pts=s.values.map((v,i)=>[p+i*(W-p-25)/span,H-p-scale.project(v)*(H-2*p)]);return '<polyline class="series-line s'+j+'" points="'+pts.map(x=>x.join(',')).join(' ')+'"/>'+pts.map((x,i)=>'<circle class="series-point s'+j+'" cx="'+x[0]+'" cy="'+x[1]+'" r="5" data-tip="'+esc(s.name+' · '+labels[i]+': '+fmt(s.values[i]))+'"></circle>').join('')}).join('')+labels.map((x,i)=>'<text x="'+(p+i*(W-p-25)/span)+'" y="'+(H-15)+'" text-anchor="middle">'+esc(x)+'</text>').join('')+'</svg>'}
function bars(labels,series,stacked=false){const W=1000,H=370,p=60,totals=labels.map((_,i)=>series.reduce((a,s)=>a+Number(s.values[i]||0),0)),all=stacked?totals:series.flatMap(s=>s.values),scale=createScale(all,1.06),group=(W-p-25)/labels.length,bw=stacked?Math.min(54,group*.55):Math.max(7,Math.min(34,(group-18)/series.length));return '<svg viewBox="0 0 '+W+' '+H+'" aria-label="Bar chart">'+scaleNote(scale,W)+'<g class="analytics-gridlines">'+grid(scale,W,H,p)+'</g>'+labels.map((label,i)=>{let stackY=H-p,total=totals[i],totalH=scale.pixels(total,H-2*p);const marks=series.map((s,j)=>{const v=Number(s.values[i]||0),h=stacked?(total>0?Math.max(v>0?2:0,totalH*v/total):0):scale.pixels(v,H-2*p),x=stacked?p+i*group+(group-bw)/2:p+i*group+(group-series.length*bw)/2+j*bw,y=stacked?stackY-h:H-p-h;if(stacked)stackY=y;return '<rect class="series-bar s'+j+'" x="'+x+'" y="'+y+'" width="'+(bw-(stacked?0:3))+'" height="'+h+'" rx="3" data-tip="'+esc(s.name+' · '+label+': '+fmt(v))+'"></rect>'}).join('');return marks+'<text x="'+(p+i*group+group/2)+'" y="'+(H-15)+'" text-anchor="middle">'+esc(label)+'</text>'}).join('')+'</svg>'}
function combo(labels,barsData,lineData){const W=1000,H=370,p=60,barScale=createScale(barsData.values,1.08),lineScale=createScale(lineData.values,1),group=(W-p-25)/labels.length,bw=Math.min(52,group*.46),pts=lineData.values.map((v,i)=>[p+i*group+group/2,H-p-lineScale.project(v)*.82*(H-2*p)]);return '<svg viewBox="0 0 '+W+' '+H+'" aria-label="Combined bar and line chart">'+scaleNote(barScale,W)+'<g class="analytics-gridlines">'+grid(barScale,W,H,p)+'</g>'+labels.map((label,i)=>{const v=barsData.values[i],h=barScale.pixels(v,H-2*p),x=p+i*group+(group-bw)/2;return '<rect class="series-bar s0" x="'+x+'" y="'+(H-p-h)+'" width="'+bw+'" height="'+h+'" rx="4" data-tip="'+esc(barsData.name+' · '+label+': '+fmt(v))+'"></rect><text x="'+(p+i*group+group/2)+'" y="'+(H-15)+'" text-anchor="middle">'+esc(label)+'</text>'}).join('')+'<polyline class="series-line s2" points="'+pts.map(x=>x.join(',')).join(' ')+'"/>'+pts.map((x,i)=>'<circle class="series-point s2" cx="'+x[0]+'" cy="'+x[1]+'" r="5" data-tip="'+esc(lineData.name+' · '+labels[i]+': '+fmt(lineData.values[i])+'%')+'"></circle>').join('')+'</svg>'}
function legend(series){return '<div class="analytics-legend">'+series.map((s,i)=>'<span><i style="background:'+colors[i%colors.length]+'"></i>'+esc(s.name)+'</span>').join('')+'</div>'}
function bind(panel){const tip=document.createElement('div');tip.className='analytics-tooltip';panel.appendChild(tip);panel.querySelectorAll('[data-tip]').forEach(mark=>{const show=e=>{tip.textContent=mark.dataset.tip;tip.classList.add('show');const r=panel.getBoundingClientRect(),x=(e.touches?.[0]?.clientX||e.clientX||r.left+80)-r.left,y=(e.touches?.[0]?.clientY||e.clientY||r.top+80)-r.top;tip.style.left=Math.max(8,Math.min(r.width-180,x+10))+'px';tip.style.top=Math.max(8,y-42)+'px'};mark.addEventListener('mouseenter',show);mark.addEventListener('mousemove',show);mark.addEventListener('touchstart',show,{passive:true});mark.addEventListener('mouseleave',()=>tip.classList.remove('show'))})}
function exportPng(panel,name){const svg=panel.querySelector('svg');if(!svg)return;const clone=svg.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='text{font:11px Arial;fill:#586c78}.analytics-gridlines line{stroke:#dbe4e8;stroke-dasharray:4 5}.series-line{fill:none;stroke-width:4}.series-line.s0{stroke:#0b506b}.series-line.s1{stroke:#19a99d}.series-line.s2{stroke:#a9d650}.series-line.s3{stroke:#e1a146}.series-point{fill:#fff;stroke-width:4}.series-point.s0{stroke:#0b506b}.series-point.s1{stroke:#19a99d}.series-point.s2{stroke:#a9d650}.series-point.s3{stroke:#e1a146}.series-bar.s0{fill:#0b506b}.series-bar.s1{fill:#19a99d}.series-bar.s2{fill:#a9d650}.series-bar.s3{fill:#e1a146}.series-bar.s4{fill:#6e78a5}';clone.prepend(style);const blob=new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=2000;canvas.height=740;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download=name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.png';a.click();URL.revokeObjectURL(url);window.notify?.('Chart PNG downloaded')};img.src=url}
window.analyticsCore={esc,fmt,line,bars,combo,legend,bind,exportPng,createScale};
})();
