(function(){
'use strict';
const root=document.getElementById('domesticDashboard'),core=window.analyticsCore;if(!root||!core)return;
const storageKey='revampTextile.domestic.v1';
const defaults={
 years:['2019','2020','2021','2022','2023','2024'],
 total:[170,138,155,166,170,179.26],household:[96,76,81,91,98,104.98],exports:[36,31,34,36,35,35.04],nonHousehold:[38,31,40,39,37,39.23],
 segments:{'Households vs Exports vs Non-Households':1,'Fibre-wise':.94,'Major Varieties':.88,'Gender-wise':.82,'Income-wise':.9,'Region-wise':.96,'Sector of manufacture':.86,'Value added':.78,'Technical textile':.72},
 regions:{'All India':1,North:.28,West:.25,South:.23,East:.14,'Central & North-East':.10},
 categories:[['Apparel',62.8,8.2],['Home Textiles',43.0,7.1],['Technical Textiles',32.3,10.8],['Yarn & Fabrics',24.1,5.6],['Handloom & Others',17.1,4.3]],
 regionRows:[['North',50.2,8.4,'Premium apparel'],['West',44.8,7.8,'Industrial textiles'],['South',41.2,7.1,'Home textiles'],['East',25.1,5.2,'Handloom'],['Central & North-East',17.9,9.6,'Emerging demand']],
 insights:[['Domestic Market Momentum','Household demand remains the largest component and continues to support broad-based market expansion.'],['Premiumisation Signal','Organised retail and branded textile products are raising average consumer spending.'],['Technical Textile Opportunity','Healthcare, mobility and infrastructure uses are growing faster than conventional categories.'],['Regional Growth White Space','Central and North-East markets show strong growth potential from a smaller base.']]
};
let data=JSON.parse(JSON.stringify(defaults));
root.classList.add('analytics-live');
root.innerHTML='<div class="analytics-head"><div><span class="overline">DOMESTIC MARKET INTELLIGENCE</span><h1>India Textile Domestic Market</h1><p>Demand, consumption, composition and growth signals for decision-ready market analysis.</p></div><div class="data-badges"><span class="official">● Official-source structure</span><span>Dummy values</span><span id="dmPeriodBadge">Latest: 2024</span></div></div><div class="analytics-filters module-filter-bar"><label>Market view<select id="dmView"></select></label><label>Reporting year<select id="dmYear"></select></label><label>Geography<select id="dmRegion"></select></label><label>Display unit<select id="dmUnit"><option value="usd">USD Billion</option><option value="inr">INR Lakh Crore</option></select></label><button id="dmReset">Reset filters</button><div class="active-filter-summary">Active selection: <b id="dmActive"></b></div></div><section class="analytics-kpis" id="dmKpis"></section><section class="analytics-chart-stack"><div class="analytics-chart-grid single"><article class="panel analytics-panel" id="dmTotalPanel"></article></div><div class="analytics-chart-grid"><article class="panel analytics-panel" id="dmHousePanel"></article><article class="panel analytics-panel" id="dmNonHousePanel"></article></div><div class="analytics-chart-grid"><article class="panel analytics-panel" id="dmCompositionPanel"></article><article class="panel analytics-panel" id="dmRegionPanel"></article></div><article class="panel scenario-box"><div><span class="overline">MARKET SCENARIO</span><h2>2030 domestic market projection</h2><p>Adjust expected annual growth to test the market outlook.</p><label>Expected annual growth <b id="dmGrowthLabel">8%</b></label><input id="dmGrowth" type="range" min="4" max="14" value="8"></div><div class="scenario-output"><small>Projected 2030 market</small><strong id="dmProjection"></strong><span id="dmScenarioSignal"></span></div></article></section><section class="panel analytics-table-panel"><div class="panel-head"><div><span class="overline">MARKET DETAIL</span><h2>Segment performance table</h2><p>Search categories and compare market size, share and growth.</p></div><div class="analytics-table-tools"><input id="dmSearch" placeholder="Search segment"></div></div><div class="analytics-table-scroll"><table><thead><tr><th>Segment</th><th>Market size</th><th>Share</th><th>YoY growth</th><th>Signal</th></tr></thead><tbody id="dmRows"></tbody></table></div></section><section class="analytics-insights" id="dmInsights"></section><footer class="analytics-footer"><div><b>Source:</b> Market for Textiles & Clothing 2024 report · Textiles Committee · Ministry of Textiles</div><span>Provisional / illustrative values are clearly marked</span></footer>';
const $=id=>document.getElementById(id),view=$('dmView'),year=$('dmYear'),region=$('dmRegion'),unit=$('dmUnit');
function fillFilters(){const keep={v:view.value,y:year.value,r:region.value};view.innerHTML=Object.keys(data.segments).map(x=>'<option>'+core.esc(x)+'</option>').join('');year.innerHTML=[...data.years].reverse().map(x=>'<option>'+core.esc(x)+'</option>').join('');region.innerHTML=Object.keys(data.regions).map(x=>'<option>'+core.esc(x)+'</option>').join('');if(data.segments[keep.v])view.value=keep.v;if(data.years.includes(keep.y))year.value=keep.y;if(data.regions[keep.r])region.value=keep.r}
const factor=()=>Number(data.segments[view.value]||1)*Number(data.regions[region.value]||1);
const convert=v=>unit.value==='inr'?v*.0837:v;
const unitName=()=>unit.value==='inr'?'₹ Lakh Cr':'USD Bn';
const display=v=>(unit.value==='inr'?'₹':'$')+core.fmt(convert(v))+(unit.value==='inr'?'L Cr':'B');
function panel(host,title,sub,svg,series,source){host.innerHTML='<div class="panel-head"><div><span class="overline">DOMESTIC ANALYTICS</span><h2>'+core.esc(title)+'</h2><p>'+core.esc(sub)+'</p></div><button class="png-only">Export PNG</button></div><div class="swipe-hint">← Swipe chart horizontally →</div><div class="analytics-scroll">'+svg+'</div>'+core.legend(series)+'<div class="analytics-source">Source: '+core.esc(source)+'</div>';host.querySelector('.png-only').onclick=()=>core.exportPng(host,title);core.bind(host)}
function filteredHistory(values){const end=Math.max(0,data.years.indexOf(year.value));return values.slice(0,end+1).map(v=>v*factor())}
function render(){
 const idx=Math.max(0,data.years.indexOf(year.value)),f=factor(),total=data.total[idx]*f,hh=data.household[idx]*f,ex=data.exports[idx]*f,nh=data.nonHousehold[idx]*f,prev=data.total[Math.max(0,idx-1)]*f,growth=idx?((total-prev)/prev*100):0;
 $('dmActive').textContent=[view.value,year.value,region.value,unitName()].join(' · ');$('dmPeriodBadge').textContent='Latest: '+year.value;
 const cards=[['Total Market Size',display(total),year.value,'◉'],['Households',display(hh),core.fmt(hh/total*100)+'% share','⌂'],['Exports',display(ex),core.fmt(ex/total*100)+'% share','◎'],['Non-Households',display(nh),core.fmt(nh/total*100)+'% share','▤']];
 $('dmKpis').innerHTML=cards.map(x=>'<article class="analytics-kpi"><span>'+x[3]+'</span><small>'+x[0]+'</small><strong>'+x[1]+'</strong><em>'+x[2]+' · <b>↗ '+core.fmt(Math.max(0,growth))+'%</b></em></article>').join('');
 const labels=data.years.slice(0,idx+1),totalSeries=[{name:'Total market ('+unitName()+')',values:filteredHistory(data.total).map(convert)}];
 panel($('dmTotalPanel'),'Market Size Trends – Total Demand ('+unitName()+')','Multi-year domestic market trajectory',core.line(labels,totalSeries),totalSeries,'Market for Textiles & Clothing 2024 report, Textiles Committee');
 const hhSeries={name:'Household demand',values:filteredHistory(data.household).map(convert)},hhShare={name:'Market share',values:data.household.slice(0,idx+1).map((v,i)=>v/data.total[i]*100)};
 panel($('dmHousePanel'),'Household Domestic Demand','Consumption and market-share movement',core.combo(labels,hhSeries,hhShare),[hhSeries,hhShare],'Textiles Committee, Ministry of Textiles');
 const nhSeries={name:'Non-household demand',values:filteredHistory(data.nonHousehold).map(convert)},nhShare={name:'Market share',values:data.nonHousehold.slice(0,idx+1).map((v,i)=>v/data.total[i]*100)};
 panel($('dmNonHousePanel'),'Non-Household Domestic Demand','Institutional and industrial textile consumption',core.combo(labels,nhSeries,nhShare),[nhSeries,nhShare],'Textiles Committee, Ministry of Textiles');
 const cats=data.categories.map(x=>x[0]),catSeries=[{name:'Market size',values:data.categories.map(x=>convert(x[1]*f))}];
 panel($('dmCompositionPanel'),'Demand Composition by Segment','Current segment market value',core.bars(cats,catSeries),catSeries,'Illustrative allocation based on Textiles Committee market structure');
 const regionSeries=[{name:year.value,values:data.regionRows.map(x=>convert(x[1]*Number(data.segments[view.value]||1)))}];
 panel($('dmRegionPanel'),'Regional Domestic Demand','Regional market size comparison',core.bars(data.regionRows.map(x=>x[0]),regionSeries),regionSeries,'Illustrative regional allocation');
 scenario();renderRows();$('dmInsights').innerHTML=data.insights.map((x,i)=>'<article><span>'+['⌂','↗','◒','⌖'][i%4]+'</span><div><h3>'+core.esc(x[0])+'</h3><p>'+core.esc(x[1])+'</p></div></article>').join('')
}
function scenario(){const idx=data.years.indexOf(year.value),base=data.total[idx]*factor(),rate=Number($('dmGrowth').value),projection=base*Math.pow(1+rate/100,2030-Number(year.value));$('dmGrowthLabel').textContent=rate+'%';$('dmProjection').textContent=display(projection);$('dmScenarioSignal').textContent=projection>=250?'On track for the $250B ambition':'Additional acceleration required'}
function renderRows(){const q=$('dmSearch').value.toLowerCase(),f=factor(),total=data.categories.reduce((a,x)=>a+x[1],0);$('dmRows').innerHTML=data.categories.filter(x=>x[0].toLowerCase().includes(q)).map(x=>'<tr><td>'+core.esc(x[0])+'</td><td>'+display(x[1]*f)+'</td><td>'+core.fmt(x[1]/total*100)+'%</td><td class="growth-up">+'+core.fmt(x[2])+'%</td><td>'+(x[2]>=9?'High growth':x[2]>=6?'Positive':'Stable')+'</td></tr>').join('')}
function save(){localStorage.setItem(storageKey,JSON.stringify(data))}
function importAll(payload){if(!payload||typeof payload!=='object')throw new Error('Invalid Domestic Market data');data=Object.assign(JSON.parse(JSON.stringify(defaults)),payload);save();fillFilters();render()}
function updateFromRows(rows){if(!rows.length)throw new Error('Domestic Market file is empty');const cols=Object.keys(rows[0]),find=re=>cols.find(c=>re.test(c)),y=find(/^year$|period/i),t=find(/total.*market|market.*size/i),h=find(/household/i),n=find(/non.?household/i),e=find(/export/i);if(!y||!t)throw new Error('Domestic file needs Year and Total Market columns.');data.years=rows.map(r=>String(r[y]));data.total=rows.map(r=>Number(r[t])||0);if(h)data.household=rows.map(r=>Number(r[h])||0);if(n)data.nonHousehold=rows.map(r=>Number(r[n])||0);if(e)data.exports=rows.map(r=>Number(r[e])||0);save();fillFilters();render()}
[view,year,region,unit].forEach(x=>x.onchange=render);$('dmReset').onclick=()=>{view.selectedIndex=0;year.selectedIndex=0;region.selectedIndex=0;unit.selectedIndex=0;render()};$('dmGrowth').oninput=scenario;$('dmSearch').oninput=renderRows;
window.domesticDashboard={getData:()=>JSON.parse(JSON.stringify(data)),importAll,updateFromRows,reset:()=>{data=JSON.parse(JSON.stringify(defaults));localStorage.removeItem(storageKey);fillFilters();render()}};
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved)data=Object.assign(data,saved)}catch(e){}
fillFilters();render();
fetch('data.json?ts='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(p=>{if(p?.domesticMarket)importAll(p.domesticMarket)}).catch(()=>{});
})();
