(function(){
document.title='India Textile & Apparel Industry Dashboard | Complete Analytics 2025-26';
const overviewTheme=document.createElement('style');overviewTheme.textContent=`
#overviewDashboard{max-width:1780px}
#overviewDashboard .overview-head{position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:30px;align-items:end;overflow:hidden;margin:0 0 16px;padding:31px 34px;border:1px solid #174962;border-radius:20px;background:linear-gradient(118deg,#092b42 0%,#0f5064 58%,#0a6b70 100%);box-shadow:0 18px 38px rgba(9,43,66,.18)}
#overviewDashboard .overview-head:before{content:"";position:absolute;right:-60px;top:-130px;width:355px;height:355px;border:1px solid rgba(181,228,93,.25);border-radius:50%;box-shadow:0 0 0 44px rgba(181,228,93,.055),0 0 0 89px rgba(181,228,93,.035)}
#overviewDashboard .overview-head:after{content:"";position:absolute;right:92px;bottom:-31px;width:135px;height:135px;opacity:.44;background:repeating-linear-gradient(90deg,#b5e45d 0 15px,transparent 15px 26px),repeating-linear-gradient(0deg,#1ab7a6 0 15px,transparent 15px 26px);transform:rotate(24deg);border-radius:22px}
#overviewDashboard .overview-head>div{position:relative;z-index:1}#overviewDashboard .overview-head .overline{color:#b8e667;font-size:10px;letter-spacing:2.1px}#overviewDashboard .overview-head h1{max-width:720px;margin:8px 0 9px;color:#fff;font-size:37px;line-height:1.08;letter-spacing:-1.2px}#overviewDashboard .overview-head p{max-width:690px;color:#c6dce4;font-size:13px;line-height:1.55}#overviewDashboard .overview-meta{min-width:182px;justify-items:start;gap:8px;padding:15px 17px;border:1px solid rgba(255,255,255,.17);border-radius:13px;background:rgba(255,255,255,.10);backdrop-filter:blur(8px)}#overviewDashboard .overview-meta span{color:#dcefeb;background:rgba(0,0,0,.13);border-color:rgba(255,255,255,.16);font-size:9px}#overviewDashboard .overview-meta span i{background:#b6e25c}#overviewDashboard .overview-meta b{color:#fff;font-size:10px}#overviewDashboard .overview-meta small{color:#b9d1d9;font-size:9px}
#overviewDashboard .overview-filters{top:80px;margin-bottom:26px;padding:15px 16px;border-color:#d5e2e6;border-radius:16px;box-shadow:0 13px 28px rgba(10,41,64,.08)}#overviewDashboard .overview-filters label{font-size:9px;color:#5a7180}#overviewDashboard .overview-filters select{height:41px;font-size:11px;background:#f8fbfc;border-color:#d5e3e7}#overviewDashboard .overview-filters button{height:41px;padding:0 17px;border-radius:9px;background:#0b4056;font-size:10px}
#overviewDashboard .ov-section-title{margin:30px 0 15px}#overviewDashboard .ov-section-title h2{font-size:29px;color:#10334b}#overviewDashboard .ov-section-title>span{font-size:10px}#overviewDashboard .overview-kpis{grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}#overviewDashboard .ov-kpi{min-height:144px;padding:19px;border-radius:16px;border-color:#d9e5e9;box-shadow:0 9px 20px rgba(10,41,64,.06);transition:transform .18s ease,box-shadow .18s ease}#overviewDashboard .ov-kpi:hover{transform:translateY(-3px);box-shadow:0 14px 27px rgba(10,41,64,.12)}#overviewDashboard .ov-kpi:before{width:5px;background:linear-gradient(#0b536d,#00a395)}#overviewDashboard .ov-kpi>span{right:17px;top:17px;width:38px;height:38px;color:#087f76;background:#e3f5f1;font-size:19px;overflow:hidden;white-space:nowrap}#overviewDashboard .ov-kpi small{font-size:11px;margin-bottom:12px;color:#617a8a}#overviewDashboard .ov-kpi strong{font-size:34px;line-height:1.04;letter-spacing:-.8px;color:#10334b}#overviewDashboard .ov-kpi em{font-size:10px}#overviewDashboard .ov-kpi>b{right:17px;bottom:17px;font-size:9px;padding:6px 9px}
#overviewDashboard .overview-targets{margin-top:30px;padding:29px;border-radius:20px;background:linear-gradient(125deg,#092b42,#0d5465)}#overviewDashboard .overview-target-grid{gap:13px}#overviewDashboard .overview-target-grid article{padding:17px;border-radius:13px}#overviewDashboard .overview-target-grid h3{font-size:13px}#overviewDashboard .overview-target-grid p strong{font-size:21px}#overviewDashboard .overview-grid{gap:15px;margin-top:16px}#overviewDashboard .panel{border-radius:16px;padding:23px}#overviewDashboard .panel-head h2{font-size:21px}#overviewDashboard .panel-head p{font-size:10px}#overviewDashboard .overview-insights{gap:13px}#overviewDashboard .overview-insights article{padding:16px;border-radius:14px}#overviewDashboard .overview-insights h3{font-size:11px}#overviewDashboard .overview-foot{margin-top:17px;padding:16px 19px}
@media(min-width:1600px){.content{max-width:1840px;padding:31px 42px 58px}#overviewDashboard .overview-head{padding:36px 40px}#overviewDashboard .overview-head h1{font-size:43px}#overviewDashboard .overview-head p{font-size:14px}#overviewDashboard .overview-filters{padding:18px}#overviewDashboard .overview-filters select,#overviewDashboard .overview-filters button{height:46px;font-size:12px}#overviewDashboard .ov-section-title h2{font-size:33px}#overviewDashboard .ov-kpi{min-height:160px;padding:23px}#overviewDashboard .ov-kpi small{font-size:12px}#overviewDashboard .ov-kpi strong{font-size:39px}#overviewDashboard .ov-kpi em{font-size:11px}#overviewDashboard .panel{padding:27px}#overviewDashboard .panel-head h2{font-size:23px}}
@media(min-width:2100px){main{margin-left:286px;width:calc(100% - 286px)}.sidebar{width:286px;padding:31px 23px}.content{max-width:2140px;padding-left:52px;padding-right:52px}.topbar{height:76px;padding:0 44px}#overviewDashboard .overview-head h1{font-size:49px}#overviewDashboard .ov-kpi strong{font-size:44px}#overviewDashboard .overview-kpis{gap:18px}}
@media(max-width:980px){#overviewDashboard .overview-head{grid-template-columns:1fr;gap:16px}#overviewDashboard .overview-meta{width:max-content}#overviewDashboard .overview-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:760px){#overviewDashboard .overview-head{padding:25px 20px;border-radius:16px}#overviewDashboard .overview-head h1{font-size:29px}#overviewDashboard .overview-head:after{display:none}#overviewDashboard .overview-meta{min-width:0}#overviewDashboard .overview-kpis{grid-template-columns:1fr}#overviewDashboard .ov-section-title h2{font-size:24px}#overviewDashboard .overview-filters{margin-bottom:20px}}
`;document.head.appendChild(overviewTheme);
const root=document.getElementById('overviewDashboard');if(!root)return;
const published={
  years:{
    '2022–23':{exports:34.7,domestic:128.4,market:163.1,employment:47.8,production:7805,share:3.8},
    '2023–24':{exports:34.45,domestic:134.5,market:168.95,employment:48.2,production:8018,share:3.9},
    '2024–25':{exports:36.95,domestic:144.21,market:179.26,employment:49,production:8337,share:4.1}
  },
  targets:[
    {key:'exports',name:'T&A Exports',target:100,unit:'USD Bn',year:2030,source:'Ministry of Textiles'},
    {key:'domestic',name:'Domestic Market',target:250,unit:'USD Bn',year:2030,source:'Textiles Committee'},
    {key:'market',name:'Total Market',target:350,unit:'USD Bn',year:2030,source:'Ministry of Textiles'},
    {key:'technical',name:'Technical Textiles',current:22,target:40,unit:'USD Bn',year:2030,source:'National Technical Textiles Mission'},
    {key:'share',name:'Global Share',target:8,unit:'%',year:2030,source:'ITC Trade Map'},
    {key:'employment',name:'Employment',target:75,unit:'Million',year:2030,source:'Ministry of Textiles'}
  ],
  sectors:{
    'All sectors':{factor:1,growth:7.2},'Cotton':{factor:.34,growth:5.8},'Silk':{factor:.08,growth:7.6},'Jute':{factor:.11,growth:4.2},'Wool':{factor:.05,growth:2.7},'MMF':{factor:.29,growth:10.4},'Handloom':{factor:.13,growth:6.1}
  },
  states:[['Gujarat',138.4,8.2,'Cotton & MMF'],['Maharashtra',126.7,6.9,'Yarn & apparel'],['Tamil Nadu',119.8,5.6,'Spinning & knitwear'],['West Bengal',108.2,4.1,'Jute & handloom'],['Karnataka',104.9,3.8,'Silk & garments']]
};
let data=JSON.parse(JSON.stringify(published)),sortAsc=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>Number(v||0),fmt=(v,d=1)=>n(v).toLocaleString('en-IN',{maximumFractionDigits:d});
function valueFor(t,profile){return t.current??profile[t.key]??0}
function status(pct){return pct>=65?['On track','good']:pct>=45?['Attention','watch']:['Critical','risk']}
function toast(msg){if(window.notify)return window.notify(msg);let el=document.querySelector('.overview-toast');if(!el){el=document.createElement('div');el.className='overview-toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('show');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('show'),2200)}
root.innerHTML=`
<section class="overview-head"><div><span class="overline">EXECUTIVE SECTOR VIEW</span><h1>Overview &amp; National Targets</h1><p>A decision-ready view of current performance, 2030 ambition and the gap between them.</p></div><div class="overview-meta"><span><i></i> Illustrative dataset</span><b>Last updated 20 Aug 2026</b><small>24 mapped sources</small></div></section>
<section class="overview-filters"><div><label>Reporting year</label><select id="ovYear"></select></div><div><label>Sector / fibre</label><select id="ovSector"></select></div><div><label>Indicator</label><select id="ovIndicator"><option value="all">All indicators</option><option value="exports">Exports</option><option value="market">Market size</option><option value="production">Production</option><option value="employment">Employment</option></select></div><div><label>Geography</label><select id="ovGeo"><option>All India</option><option>Gujarat</option><option>Maharashtra</option><option>Tamil Nadu</option><option>West Bengal</option></select></div><button id="ovReset">Reset filters</button></section>
<section class="ov-section-title"><div><span class="overline">INDUSTRY PULSE</span><h2>Performance at a glance</h2></div><span id="ovFilterNote"></span></section><section class="overview-kpis" id="ovKpis"></section>
<section class="overview-targets" id="ovTargetsWrap"><div class="ov-section-title light"><div><span class="overline">INDIA @ 2030</span><h2>Vision targets &amp; progress</h2><p>Achievement, remaining gap and status calculated automatically.</p></div><button id="copySummary">Copy executive summary</button></div><div class="overview-target-grid" id="ovTargets"></div></section>
<section class="overview-grid wide"><article class="panel ov-chart"><div class="panel-head"><div><span class="overline">MULTI-YEAR TREND</span><h2>Overall performance trend</h2><p>Selected indicator across available reporting periods</p></div><button class="ov-png">Export PNG</button></div><div class="ov-chart-scroll"><div id="ovTrend" class="ov-svg-host"></div></div><div class="ov-source">Source: Ministry of Textiles · Textiles Committee</div></article><article class="panel executive-card"><span class="overline">AUTOMATED BRIEF</span><h2>Executive summary</h2><p id="ovSummary"></p><div id="ovAlerts"></div></article></section>
<section class="overview-grid"><article class="panel ov-chart"><div class="panel-head"><div><span class="overline">SECTOR COMPARISON</span><h2>Relative performance</h2><p>Current year index and growth comparison</p></div><button class="ov-png">Export PNG</button></div><div class="ov-compare-controls"><label>Compare with <select id="ovCompare"></select></label></div><div class="ov-chart-scroll"><div id="ovSectorChart" class="ov-svg-host"></div></div><div class="ov-source">Illustrative composite index</div></article><article class="panel scenario-card"><span class="overline">SCENARIO SIMULATOR</span><h2>Can exports reach the 2030 target?</h2><label>Expected annual growth <b id="growthLabel">15%</b></label><input id="growthRange" type="range" min="5" max="25" value="15"><div class="scenario-result"><small>Projected 2030 exports</small><strong id="projectedExport"></strong><span id="scenarioStatus"></span></div><div class="scenario-bars"><i id="scenarioProgress"></i></div><p id="scenarioText"></p></article></section>
<section class="panel target-table-panel"><div class="panel-head"><div><span class="overline">TARGET ACHIEVEMENT MATRIX</span><h2>Current position against 2030 ambition</h2><p>Click a column heading to sort the table.</p></div><div class="table-tools"><input id="targetSearch" placeholder="Search indicator"><select id="statusFilter"><option value="all">All status</option><option value="good">On track</option><option value="watch">Attention</option><option value="risk">Critical</option></select></div></div><div class="ov-table-scroll"><table><thead><tr><th data-sort="name">Indicator ↕</th><th>Current</th><th>Target</th><th data-sort="pct">Achievement ↕</th><th>Remaining gap</th><th>Year</th><th>Status</th><th>Source</th></tr></thead><tbody id="targetRows"></tbody></table></div></section>
<section class="overview-grid"><article class="panel state-rank"><div class="panel-head"><div><span class="overline">STATE SNAPSHOT</span><h2>Leading production states</h2><p>Composite performance index</p></div><button id="stateDrill">Open Statewise Stats →</button></div><div id="stateRanks"></div></article><article class="panel decision-panel"><span class="overline">DECISION SIGNALS</span><h2>Alerts &amp; opportunities</h2><div id="decisionSignals"></div></article></section>
<section class="overview-insights" id="ovInsights"></section>
<section class="overview-foot"><div><span>DATA CONFIDENCE</span><b>Illustrative structure · Ready for official replacement</b></div><div><span>Ministry of Textiles</span><span>Textiles Committee</span><span>ITC Trade Map</span><span>24 sources</span></div></section>`;
const $=id=>document.getElementById(id),year=$('ovYear'),sector=$('ovSector'),indicator=$('ovIndicator'),geo=$('ovGeo');
year.innerHTML=Object.keys(data.years).reverse().map(x=>`<option>${x}</option>`).join('');sector.innerHTML=Object.keys(data.sectors).map(x=>`<option>${x}</option>`).join('');$('ovCompare').innerHTML=Object.keys(data.sectors).filter(x=>x!=='All sectors').map(x=>`<option>${x}</option>`).join('');
function adjustedProfile(){const base=data.years[year.value],s=data.sectors[sector.value]||data.sectors['All sectors'],factor=sector.value==='All sectors'?1:s.factor;return {...base,exports:base.exports*factor,domestic:base.domestic*factor,market:base.market*factor,production:base.production*factor,employment:base.employment*(sector.value==='All sectors'?1:Math.max(.12,factor)),growth:s.growth}}
function kpis(p){const prevKeys=Object.keys(data.years),idx=prevKeys.indexOf(year.value),prev=data.years[prevKeys[Math.max(0,idx-1)]],s=data.sectors[sector.value],factor=sector.value==='All sectors'?1:s.factor;return[
  ['Total Production',fmt(p.production,0),'Mn Kg',((p.production-prev.production*factor)/(prev.production*factor)*100)||0,'◫','Production'],
  ['Total Exports','$'+fmt(p.exports,2)+'B','USD billion',((p.exports-prev.exports*factor)/(prev.exports*factor)*100)||0,'↗','International Trade'],
  ['Domestic Market','$'+fmt(p.domestic,2)+'B','USD billion',((p.domestic-prev.domestic*factor)/(prev.domestic*factor)*100)||0,'⌂','Domestic Market'],
  ['Total Market','$'+fmt(p.market,2)+'B','Combined value',((p.market-prev.market*factor)/(prev.market*factor)*100)||0,'◉','Domestic Market'],
  ['Employment',fmt(p.employment,1)+'M','Direct jobs',((p.employment-prev.employment*(sector.value==='All sectors'?1:Math.max(.12,factor)))/(prev.employment*(sector.value==='All sectors'?1:Math.max(.12,factor)))*100)||0,'♙','Overview & Targets'],
  ['Global Share',fmt(p.share,1)+'%','Global textile trade',((p.share-prev.share)/prev.share*100)||0,'◎','International Trade']];}
function renderKpis(p){$('ovKpis').innerHTML=kpis(p).map((x,i)=>`<button class="ov-kpi k${i}" data-module="${x[5]}"><span aria-hidden="true">${x[4]}</span><small>${x[0]}</small><strong>${x[1]}</strong><em>${x[2]}</em><b class="${x[3]>=0?'up':'down'}">${x[3]>=0?'↗':'↘'} ${fmt(Math.abs(x[3]),1)}%</b></button>`).join('');root.querySelectorAll('.ov-kpi').forEach(x=>x.onclick=()=>navigate(x.dataset.module))}
function targets(p){return data.targets.map(t=>{const current=valueFor(t,p),pct=Math.min(100,current/t.target*100),gap=Math.max(0,t.target-current),st=status(pct);return{...t,current,pct,gap,status:st[0],statusClass:st[1]}})}
function renderTargets(p){$('ovTargets').innerHTML=targets(p).map((t,i)=>`<article><div><span>0${i+1}</span><b class="${t.statusClass}">${t.status}</b></div><h3>${t.name}</h3><p><strong>${fmt(t.current,2)}</strong> <em>${t.unit}</em><i>→</i><strong>${fmt(t.target,1)}</strong> <em>${t.unit}</em></p><div class="ov-progress"><i style="width:${t.pct}%"></i></div><small>${fmt(t.pct,1)}% achieved · Gap ${fmt(t.gap,2)} ${t.unit}</small></article>`).join('')}
function lineSvg(values,labels,name){const W=820,H=290,l=62,b=48,top=26,max=Math.max(...values)*1.15,min=0,px=i=>l+i*(W-l-25)/(values.length-1),py=v=>H-b-(v-min)/(max-min)*(H-b-top),ticks=[0,.25,.5,.75,1],points=values.map((v,i)=>`${px(i)},${py(v)}`).join(' ');return`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(name)} trend"><g class="ov-grid-lines">${ticks.map(t=>`<line x1="${l}" y1="${top+t*(H-b-top)}" x2="${W-25}" y2="${top+t*(H-b-top)}"></line><text x="${l-10}" y="${top+t*(H-b-top)+4}" text-anchor="end">${fmt(max*(1-t),1)}</text>`).join('')}</g><polyline class="ov-line" points="${points}"></polyline>${values.map((v,i)=>`<circle cx="${px(i)}" cy="${py(v)}" r="6" tabindex="0" data-tip="${esc(labels[i]+' · '+name+': '+fmt(v,2))}"></circle><text x="${px(i)}" y="${H-16}" text-anchor="middle">${esc(labels[i])}</text>`).join('')}</svg>`}
function barSvg(items,compare){const W=820,H=315,l=60,b=58,top=26,max=Math.max(...items.map(x=>x[1]),compare[1])*1.15,g=(W-l-25)/(items.length+1),bw=46;return`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Sector comparison"><g class="ov-grid-lines">${[0,.25,.5,.75,1].map(t=>`<line x1="${l}" y1="${top+t*(H-b-top)}" x2="${W-25}" y2="${top+t*(H-b-top)}"></line><text x="${l-9}" y="${top+t*(H-b-top)+4}" text-anchor="end">${fmt(max*(1-t),0)}</text>`).join('')}</g>${[...items,compare].map((x,i)=>{const h=x[1]/max*(H-b-top),left=l+i*g+(g-bw)/2;return`<rect x="${left}" y="${H-b-h}" width="${bw}" height="${h}" rx="6" class="${i===items.length?'compare':''}" tabindex="0" data-tip="${esc(x[0]+': '+fmt(x[1],1)+' index')}"></rect><text x="${left+bw/2}" y="${H-20}" text-anchor="middle">${esc(x[0])}</text>`}).join('')}</svg>`}
function bindTips(host){let tip=root.querySelector('.ov-tooltip');if(!tip){tip=document.createElement('div');tip.className='ov-tooltip';root.appendChild(tip)}host.querySelectorAll('[data-tip]').forEach(mark=>{const show=e=>{tip.textContent=mark.dataset.tip;tip.classList.add('show');const r=root.getBoundingClientRect(),x=(e.clientX||mark.getBoundingClientRect().left)-r.left,y=(e.clientY||mark.getBoundingClientRect().top)-r.top;tip.style.left=x+12+'px';tip.style.top=y-40+'px'};mark.onmouseenter=show;mark.onmousemove=show;mark.onfocus=show;mark.onclick=show;mark.onmouseleave=mark.onblur=()=>tip.classList.remove('show')})}
function renderCharts(p){const keys=Object.keys(data.years),metric=indicator.value==='all'?'exports':indicator.value,labels=keys,vals=keys.map(y=>data.years[y][metric]??data.years[y].market);$('ovTrend').innerHTML=lineSvg(vals,labels,metric[0].toUpperCase()+metric.slice(1));const list=Object.entries(data.sectors).filter(([k])=>k!=='All sectors').slice(0,5).map(([k,v])=>[k,100+v.growth*2]);const comp=$('ovCompare').value,compData=[comp,100+(data.sectors[comp]?.growth||0)*2];$('ovSectorChart').innerHTML=barSvg(list.filter(x=>x[0]!==comp),compData);bindTips($('ovTrend'));bindTips($('ovSectorChart'))}
function summary(p){const t=targets(p),exportT=t[0],best=Object.entries(data.sectors).filter(([k])=>k!=='All sectors').sort((a,b)=>b[1].growth-a[1].growth)[0];return`${sector.value} recorded ${fmt(p.exports,2)} USD Bn in exports and a total market value of ${fmt(p.market,2)} USD Bn for ${year.value}. Export target achievement stands at ${fmt(exportT.pct,1)}%, leaving a gap of ${fmt(exportT.gap,2)} USD Bn. ${best[0]} is the fastest-growing tracked segment at ${best[1].growth}%.`}
function renderSummary(p){$('ovSummary').textContent=summary(p);const t=targets(p),alerts=[['↗','Growth opportunity','MMF is the fastest-growing tracked segment.'],['!','Largest gap',`${t.sort((a,b)=>b.gap-a.gap)[0].name} needs the greatest absolute progress.`],['◷','Data status','Latest values include illustrative and provisional indicators.']];$('ovAlerts').innerHTML=alerts.map(x=>`<div><span>${x[0]}</span><p><b>${x[1]}</b><small>${x[2]}</small></p></div>`).join('');$('decisionSignals').innerHTML=alerts.map(x=>`<article><span>${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join('')}
function renderTable(p){let list=targets(p),q=$('targetSearch').value.toLowerCase(),sf=$('statusFilter').value;list=list.filter(x=>x.name.toLowerCase().includes(q)&&(sf==='all'||x.statusClass===sf));if(sortAsc)list.sort((a,b)=>a.pct-b.pct);$('targetRows').innerHTML=list.map(t=>`<tr><td><b>${t.name}</b></td><td>${fmt(t.current,2)} ${t.unit}</td><td>${fmt(t.target,1)} ${t.unit}</td><td><div class="table-progress"><i style="width:${t.pct}%"></i></div>${fmt(t.pct,1)}%</td><td>${fmt(t.gap,2)} ${t.unit}</td><td>${t.year}</td><td><span class="table-status ${t.statusClass}">${t.status}</span></td><td>${t.source}</td></tr>`).join('')}
function renderStates(){const max=Math.max(...data.states.map(x=>x[1]));$('stateRanks').innerHTML=data.states.map((x,i)=>`<div><span>0${i+1}</span><p><b>${x[0]}</b><small>${x[3]}</small></p><div><i style="width:${x[1]/max*100}%"></i></div><strong>${x[1]}</strong><em>+${x[2]}%</em></div>`).join('')}
function renderInsights(){const cards=[['◎','Target visibility','Six national ambitions are tracked with achievement, gap and status.'],['↗','Export recovery','Exports improved in 2024–25 after a softer previous year.'],['◒','Synthetic momentum','MMF shows the strongest illustrative growth among tracked fibres.'],['⌖','Regional concentration','Five states lead organised textile production and processing.'],['✓','Data confidence','Provisional and illustrative values are visibly identified.'],['▤','Report ready','The executive summary can be copied directly into a working note.']];$('ovInsights').innerHTML=cards.map(x=>`<article><span>${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join('')}
function scenario(){const rate=n($('growthRange').value),base=data.years['2024–25'].exports,years=6,projection=base*Math.pow(1+rate/100,years),pct=Math.min(100,projection/100*100);$('growthLabel').textContent=rate+'%';$('projectedExport').textContent='$'+fmt(projection,1)+'B';$('scenarioProgress').style.width=pct+'%';$('scenarioStatus').textContent=projection>=100?'Target achievable':'Target shortfall';$('scenarioStatus').className=projection>=100?'good':'watch';$('scenarioText').textContent=projection>=100?`At ${rate}% annual growth, the target can be exceeded by $${fmt(projection-100,1)}B.`:`At ${rate}% annual growth, the projected gap is $${fmt(100-projection,1)}B.`}
function navigate(label){const btn=[...document.querySelectorAll('#moduleNav button')].find(b=>b.querySelector('span').textContent.trim()===label);if(btn)btn.click()}
function exportPng(button){const panel=button.closest('.ov-chart'),host=panel.querySelector('.ov-svg-host'),svg=host.querySelector('svg');if(!svg)return;const clone=svg.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='text{font:12px Arial;fill:#536775}.ov-grid-lines line{stroke:#dce5e9;stroke-dasharray:4 5}.ov-line{fill:none;stroke:#711044;stroke-width:4}circle{fill:white;stroke:#711044;stroke-width:4}rect{fill:#711044}.compare{fill:#23ad6b}';clone.prepend(style);const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'})),img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=1640;canvas.height=630;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,1640,630);ctx.drawImage(img,0,0,1640,630);const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='overview-chart.png';a.click();URL.revokeObjectURL(url);toast('Chart PNG downloaded')};img.src=url}
function render(){const p=adjustedProfile();$('ovFilterNote').textContent=`${year.value} · ${sector.value} · ${geo.value}`;renderKpis(p);renderTargets(p);renderCharts(p);renderSummary(p);renderTable(p);renderStates();renderInsights();scenario()}
[year,sector,indicator,geo,$('ovCompare')].forEach(el=>el.onchange=render);$('ovReset').onclick=()=>{year.selectedIndex=0;sector.value='All sectors';indicator.value='all';geo.value='All India';render();toast('Overview filters reset')};$('growthRange').oninput=scenario;$('targetSearch').oninput=()=>renderTable(adjustedProfile());$('statusFilter').onchange=()=>renderTable(adjustedProfile());root.querySelectorAll('th[data-sort]').forEach(th=>th.onclick=()=>{sortAsc=!sortAsc;renderTable(adjustedProfile())});root.querySelectorAll('.ov-png').forEach(b=>b.onclick=()=>exportPng(b));$('copySummary').onclick=async()=>{try{await navigator.clipboard.writeText($('ovSummary').textContent);toast('Executive summary copied')}catch(e){toast('Copy is unavailable in this browser')}};$('stateDrill').onclick=()=>navigate('Statewise Stats');
window.overviewDashboard={getData:()=>JSON.parse(JSON.stringify(data)),importData:payload=>{if(payload&&payload.years){data=payload;render()}},importAll:payload=>{if(!payload?.years)throw new Error('Invalid Overview data');data=payload;render()},updateIndicators:rows=>{rows.forEach(r=>{const y=r.Year||r.year,name=r.Indicator||r.indicator,val=n(r.Current||r.current||r.Value||r.value);if(data.years[y]&&name)data.years[y][String(name).toLowerCase().replace(/\s+/g,'')]=val});render()}};
fetch('data.json?ts='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(j=>{if(j?.overview){data=j.overview;render()}}).catch(()=>{});render();
})();
