(function(){
const root=document.getElementById('productionDashboard');if(!root)return;
const catalogue={
'All Fibres Overview':{kpis:[['Total Tracked Production','8,337','Mn Kg'],['Leading Fibre','Cotton','Largest category'],['Fibre Categories','5','Tracked categories'],['Fastest Growth','MMF','Latest trend']],charts:[{type:'bar',title:'Fibre Production Overview (2024–25) (Mn Kg)',labels:['Cotton','MMF','Jute','Silk','Wool'],series:[['Production',[5120,1987,1310,41.1,34.6]]],source:'O/o Textile Commissioner · Central Silk Board · Office of the Jute Commissioner · Basics of Animal Husbandry Statistics 2025'}],insights:[['Natural Fibre Scale','Cotton remains the largest tracked fibre by production volume.'],['Synthetic Transition','MMF capacity is expanding to serve apparel and technical-textile demand.'],['Diverse Fibre Base','India produces cotton, MMF, jute, silk and wool at commercial scale.'],['Decision-ready Comparison','The overview standardises multiple sources for quick sector comparison.']]},
'Cotton':{kpis:[['Latest Production (2025–26)','292.15','Lakh bales'],['Top State','Maharashtra','72.66 lakh bales'],['Total States','11','Major producers'],['Global Rank','#2','World position']],charts:[{type:'line',title:'Cotton Production Trends (in lakh bales of 170 kgs each)',labels:['2014–15','2015–16','2016–17','2017–18','2018–19','2019–20','2020–21','2021–22','2022–23','2023–24','2024–25','2025–26 (P)'],series:[['Production',[386,333,346,371,334,366,352,312,338,326,298,292.15]]],source:'O/o Textile Commissioner'},{type:'grouped',title:'Cotton – State-wise Production (lakh bales of 170 kgs each)',labels:['Maharashtra','Gujarat','Telangana','Karnataka','Madhya Pradesh','Andhra Pradesh','Odisha','Punjab','Tamil Nadu','Others'],series:[['2024–25',[73.5,72.1,57.2,22.5,15.1,12.1,8.3,4.2,2.1,.6]],['2025–26 (P)',[79.1,66.2,60.4,21.3,9.8,10.1,8.5,3.2,1.2,.5]]],source:'O/o Textile Commissioner (P = Provisional)'}],insights:[['Premium Branding – Kasturi Cotton Bharat','Certified premium cotton supports freshness, whiteness, strength and fibre traceability.'],['Rapid Farm-to-Fashion Delivery','Integrated textile parks can reduce lead times from spinning through processing.'],['Zero-Duty Competitive Pricing','Trade agreements can improve price competitiveness in major export markets.'],['Why Choose Indian Cotton?','Ethically grown and digitally traced cotton supports global fashion supply chains.']]},
'Silk':{kpis:[['Total Production','41,121','MT'],['Mulberry Share','75.67%','Dominant variety'],['Varieties','4','Main types'],['Growth','+5.7%','YoY change']],charts:[{type:'line',title:'Silk Production Trends (MT)',labels:['2020–21','2021–22','2022–23','2023–24','2024–25','2025–26 (Apr–Jun)'],series:[['Total Raw Silk',[34000,35100,36700,39000,41121,35400]]],source:'Central Silk Board'},{type:'grouped',title:'Variety-wise Silk Production Trends (MT)',labels:['2020–21','2021–22','2022–23','2023–24','2024–25','2025–26 (Apr–Jun)'],series:[['Eri',[6900,7200,7200,7100,7700,6500]],['Muga',[650,700,720,760,821,500]],['Mulberry',[23700,25700,27400,29700,30900,26600]],['Tasar',[2500,1500,1300,1500,1700,1800]]],source:'Central Silk Board'},{type:'grouped',title:'Silk – State-wise Production (MT)',labels:['Andhra Pradesh','Assam','Tamil Nadu','West Bengal','Meghalaya','Jharkhand','Maharashtra','Telangana','Uttar Pradesh','Others'],series:[['2022–23',[11800,9200,5600,1900,1050,700,560,390,240,3020]],['2023–24',[12450,10300,5600,2000,1100,880,610,440,280,2720]]],source:'Indian Silk Export Promotion Council'}],insights:[['Global Consumer Hub','India is the world’s largest consumer of silk, sustaining a robust domestic ecosystem.'],['The All-Varieties Advantage','India produces Mulberry, Eri, Tasar and Muga silk.'],['Ahimsa & Ethical Luxury','Eri silk is harvested without harming silkworms.'],['GI-Tag Prestige','Indian silk benefits from recognised geographical indications.'],['Digital Traceability','Tracking can help buyers verify origin and quality.'],['Heritage & Authority','Four silks and centuries of textile mastery strengthen India’s position.']]},
'Jute':{kpis:[['Latest Raw Jute','75','Lakh bales'],['Latest Jute Goods','1,043.9','Thousand MT'],['Global Rank','#1','World position'],['Export Potential','High','Eco-friendly']],charts:[{type:'bar',title:'Raw Jute Production Trends (in lakh bales of 180 kgs each)',labels:['2019–20','2020–21','2021–22','2022–23','2023–24','2024–25','2025–26'],series:[['Production',[64,57,82,83,82,69,75]]],source:'Office of the Jute Commissioner'},{type:'stacked',title:"Production of Jute Goods (In 000' MT)",labels:['2019–20','2020–21','2021–22','2022–23','2023–24','2024–25','2025–26'],series:[['Hessian',[105,115,120,118,108,100,102]],['Sacking',[940,745,870,1040,1055,975,1150]],['Others',[120,105,95,90,85,75,130]]],source:'Office of the Jute Commissioner'},{type:'grouped',title:"Raw Jute – State-wise Production (In 000' Bales)",labels:['West Bengal','Bihar','Assam','Others','Total'],series:[['2022–23',[7700,720,650,160,9230]],['2023–24',[7810,930,660,170,9570]],['2024–25',[6900,800,700,180,8580]],['2025–26',[6550,780,690,200,8220]]],source:'Office of the Jute Commissioner'}],insights:[["World’s #1 Producer",'India is a leading producer of raw jute and jute goods.'],['End-to-End Self-Reliance','India maintains a complete cultivation-to-manufacturing value chain.'],['Mandatory Packaging Acts','Packaging requirements create a stable domestic demand base.'],['The Plastic-Ban Opportunity','Restrictions on single-use plastics can increase demand for jute bags.'],['Carbon-Negative Hero','Jute supports low-carbon and circular material strategies.'],['100% Biodegradable','Jute decomposes naturally without persistent microplastics.']]},
'Wool':{kpis:[['Latest Production','34.6','Million Kg'],['Trend','+2.67%','Growth'],['States & UTs','18','Tracked regions'],['Global Rank','#9','World position']],charts:[{type:'area',title:'Wool Production Trends (Mn Kg)',labels:['2014–15','2015–16','2016–17','2017–18','2018–19','2019–20','2020–21','2021–22','2022–23','2023–24','2024–25'],series:[['Production',[48.1,44.2,44.1,42.2,40.9,37.7,37.6,34.1,34.7,34.7,35.4]]],source:'Basics of Animal Husbandry Statistics 2025'},{type:'grouped',title:"Wool – State-wise Production ('000 Kg)",labels:['Rajasthan','Jammu & Kashmir','Gujarat','Himachal Pradesh','Uttarakhand','West Bengal','Haryana','Karnataka','Punjab','Others'],series:[['2023–24',[15900,7800,2100,1700,1500,900,700,650,550,1350]],['2024–25',[16400,8000,2200,1800,1550,920,720,680,570,1380]]],source:'Basics of Animal Husbandry Statistics 2025'}],insights:[['Global Ranking','India is the 9th-largest wool producer globally.'],['Regional Powerhouse','Rajasthan and Jammu & Kashmir lead domestic wool output.'],['The Pashmina Monopoly','Geographical indications protect premium Pashmina and Angora fibres.'],['The Green Frontier','Wool is renewable, biodegradable and suitable for circular fashion.']]},
'Man-Made Fibres (MMF)':{kpis:[['Latest Production','1,986.95','Mn Kg staple fibre'],['Polyester Share','92.47%','Staple fibre'],['The Hub','Surat','Synthetic capital'],['Global Rank','#2','World position']],charts:[{type:'grouped',title:'Production of MMF Staple Fibre (Mn Kg)',labels:['2019–20','2020–21','2021–22','2022–23','2023–24 (P)','2024–25 (P)'],series:[['Acrylic',[105,82,108,105,102,104]],['Polyester',[1220,1100,1510,1500,1360,1365]],['Polypropylene',[8,7,9,8,7,8]],['Viscose',[560,450,540,535,520,525]]],source:'O/o Textile Commissioner (P = Provisional)'},{type:'grouped',title:'Production of Filament Yarn (Mn Kg)',labels:['2019–20','2020–21','2021–22','2022–23','2023–24 (P)','2024–25 (P)'],series:[['Nylon',[55,48,62,67,64,66]],['Polyester',[1580,1440,1880,1760,1530,1535]],['Polypropylene',[18,17,20,19,18,18]],['Viscose',[45,42,51,49,47,48]]],source:'O/o Textile Commissioner (P = Provisional)'}],insights:[['Export Target 2030','India is targeting strong growth in MMF textile exports.'],['Market Share Expansion','Synthetic fibres account for most global fibre consumption.'],['Technical Textiles Leadership','MMF is central to healthcare, automotive and infrastructure textiles.'],['Shift in Global Demand','Production is realigning toward activewear and performance apparel.'],['Favourable Trade Deals','New trade access can support multi-billion-dollar export opportunities.'],['The PLI Advantage','Production-linked incentives support MMF and technical-textile capacity.']]},
'Handloom':{kpis:[['Latest Production','4,260','Million metres'],['Workforce','35.2 Lakh','Artisans'],['Women Weavers','72.3%','Workforce share'],['Coverage','28 States','Pan-India']],charts:[{type:'line',title:'Production of Handloom (Qty. in Million Mtrs.)',labels:['2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023','2024'],series:[['Production',[2000,2150,2300,2470,2640,2810,2960,3120,3280,3450,3600,3780,3940,4090,4260]]],note:'Figures are estimates and may change as additional data becomes available.',source:'Handloom Census & Market for Textiles & Clothing 2024 report, Textiles Committee, MoT'}],insights:[['Handloom: A Living Cultural Heritage','Traditional looms preserve centuries-old techniques and regional identities.'],['Economic Backbone of Rural India','The sector supports livelihoods for millions of artisans.'],['Empowering Women Weavers','Women form approximately 72.3% of the handloom workforce.'],['Digital Empowerment through E-Commerce','Digital platforms connect artisans directly with wider markets.']]}
};
const productionStorageKey='revampTextile.production.v1',defaultCatalogue=JSON.parse(JSON.stringify(catalogue));
async function loadPublishedData(){try{const response=await fetch('data.json?ts='+Date.now(),{cache:'no-store'});if(response.ok){const payload=await response.json(),published=payload.production||payload;if(published&&typeof published==='object')Object.assign(catalogue,published)}}catch(error){console.info('Published data file not available; using dashboard defaults')}try{const saved=JSON.parse(localStorage.getItem(productionStorageKey)||'null');if(saved&&typeof saved==='object')Object.assign(catalogue,saved)}catch(error){console.warn('Saved production data could not be loaded',error)}refreshOptions();}
const icons=['◒','⌖','▦','↗'],esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
root.innerHTML='<div class="module-title"><div><span class="overline">PRODUCTION INTELLIGENCE</span><h1>Textile Production Dashboard</h1><p>Explore production, state contribution and sector signals by fibre.</p></div><span class="production-badge">Illustrative data</span></div><div class="module-filter-bar production-main-filter"><span>⌕</span><label>Fibre category</label><select id="productionFibre"></select><em>Selection updates the full page</em></div><section class="production-visual" id="productionVisual" aria-live="polite"></section><section class="production-kpis" id="productionKpis"></section><section class="production-chart-stack" id="productionCharts"></section><section class="production-insights" id="productionInsights"></section>';
const select=document.getElementById('productionFibre'),visualHost=document.getElementById('productionVisual'),kpiHost=document.getElementById('productionKpis'),chartHost=document.getElementById('productionCharts'),insightHost=document.getElementById('productionInsights');select.innerHTML=Object.keys(catalogue).map(x=>'<option>'+x+'</option>').join('');
const fmt=n=>n>=1000?Math.round(n).toLocaleString('en-IN'):n>=10?Math.round(n):Number(n.toFixed(1));
const chartScale=(values,multiplier=1.12)=>window.AdaptiveChartScale?.create(values,multiplier)||{max:Math.max(1,...values)*multiplier,adaptive:false,project:v=>Number(v||0)/(Math.max(1,...values)*multiplier),tick:t=>Math.max(1,...values)*multiplier*(1-t),pixels:(v,size,min=4)=>Number(v)>0?Math.max(min,Number(v)/(Math.max(1,...values)*multiplier)*size):0};
const scaleLabel=(scale,W)=>scale.adaptive?'<text class="adaptive-scale-label" x="'+(W-26)+'" y="20" text-anchor="end">Adaptive visibility scale · hover for exact values</text>':'';
/* All Fibres Overview is calculated from the latest fibre charts. It is never a separate manual dataset. */
const fibreMeta={
  Cotton:{factor:17,unit:'Mn Kg',from:'lakh bales × 170 kg'},
  Silk:{factor:.001,unit:'Mn Kg',from:'MT'},
  Jute:{factor:18,unit:'Mn Kg',from:'lakh bales × 180 kg'},
  Wool:{factor:1,unit:'Mn Kg',from:'Mn Kg'},
  'Man-Made Fibres (MMF)':{factor:1,unit:'Mn Kg',from:'Mn Kg'},
  Handloom:{factor:1,unit:'Million metres',from:'Million metres',separate:true}
};
/* Replace src values with assets/images/... later; the rendering code does not need to change. */
const fibreVisuals={
  'All Fibres Overview':{src:'https://gumlet.assettype.com/swarajya/2021-09/9fd682d8-fa91-4c36-a590-f6480e57a295/pjimage__49_.jpg?auto=format%2Ccompress&ogImage=true&w=1200',source:'https://swarajyamag.com/business/indias-textile-handicraft-exports-at-record-44-billion-in-fy22-official',eyebrow:'INDIA FIBRE ECOSYSTEM',title:'From natural heritage to modern manufacturing',text:'A connected view of cotton, silk, jute, wool, MMF and handloom production.'},
  Cotton:{src:'https://manditoday.com/_next/image?q=75&url=%2Fcotton-hero-field.png&w=3840',source:'https://manditoday.com/articles/cotton-mandi-prices',eyebrow:'NATURAL FIBRE',title:'Cotton: farm-to-fashion scale',text:'Track national output, annual movement and leading producing states.'},
  Silk:{src:'https://assamstory.com/wp-content/uploads/2023/11/Sualkuchi-Silk-Farm.jpg',source:'https://assamstory.com/sualkuchi-a-unique-weavers-village/',eyebrow:'PREMIUM NATURAL FIBRE',title:'Silk: craft, variety and value',text:'Compare total raw silk, varieties and regional production performance.'},
  Jute:{src:'https://www.aljazeera.com/wp-content/uploads/2021/10/000_96K2XJ.jpg?fit=1170%2C780&quality=80',source:'https://www.aljazeera.com/gallery/2021/10/7/photos-india-rebrands-jute-as-alternative-to-plastic',eyebrow:'CIRCULAR MATERIAL',title:'Jute: India’s biodegradable advantage',text:'Follow raw jute supply, goods production and state contribution.'},
  Wool:{src:'https://images.squarespace-cdn.com/content/v1/60be203816d6b011fa63f746/0957813d-a7fb-4899-9ec9-95783ccf914e/desi-oon-54.png',source:'https://www.desioonhub.org/',eyebrow:'ANIMAL FIBRE',title:'Wool: regional livelihoods and premium craft',text:'View production trends and the states shaping India’s wool economy.'},
  'Man-Made Fibres (MMF)':{src:'https://www.grasim.com/Upload/Content_Files/grasim-plant-bharuch.jpg',source:'https://www.grasim.com/media/press-reports/heroes-paving-the-way-to-an-atmanirbhar-bharat',eyebrow:'MODERN MATERIALS',title:'MMF: capacity for the next textile economy',text:'Monitor staple fibre, filament yarn and synthetic production momentum.'},
  Handloom:{src:'https://images.yourstory.com/cs/210/3fb20ae02dc911e9af58c17e6cc3d915/shutterstock1946653654-1738240050637.jpg',source:'https://yourstory.com/ys-life/honouring-indias-textile-legacy',eyebrow:'LIVING HERITAGE',title:'Handloom: production with cultural value',text:'Connect output trends with artisan livelihoods and traditional knowledge.'}
};
function renderVisual(key){
  const item=fibreVisuals[key]||fibreVisuals['All Fibres Overview'];
  const category=catalogue[key]||{},primary=category.kpis?.[0]||['Latest production','–','Awaiting data'];
  visualHost.classList.remove('image-failed');
  visualHost.innerHTML='<div class="production-visual-image"><img src="'+esc(item.src)+'" alt="" loading="lazy" referrerpolicy="no-referrer"><span class="production-image-fallback" aria-hidden="true">◫</span></div><div class="production-visual-shade" aria-hidden="true"></div><div class="production-visual-copy"><span class="overline">'+esc(item.eyebrow)+'</span><h2>'+esc(item.title)+'</h2><p>'+esc(item.text)+'</p><a href="'+esc(item.source)+'" target="_blank" rel="noopener noreferrer">Image reference ↗</a></div><div class="production-visual-stat"><small>'+esc(primary[0])+'</small><b>'+esc(primary[1])+'</b><span>'+esc(primary[2]||key)+'</span></div>';
  const image=visualHost.querySelector('img');
  image.onerror=()=>{visualHost.classList.add('image-failed');image.removeAttribute('src')};
}
function latestProductionPoint(category){
  const charts=(catalogue[category]?.charts||[]).filter(c=>!/(state.?wise|variety.?wise|jute goods|filament yarn)/i.test(c.title||''));
  const chart=charts.find(c=>/(trend|production)/i.test(c.title||''))||charts[0];
  const values=chart?.series?.[0]?.[1]||[];
  for(let i=values.length-1;i>=0;i--){const value=Number(values[i]);if(Number.isFinite(value)){
    const earlier=Array.from(values.slice(0,i)).reverse().map(Number).find(Number.isFinite);
    return {value,label:chart.labels?.[i]||'Latest',previous:earlier,source:chart.source||'Uploaded fibre data'};
  }}
  return null;
}
function formatAutoValue(value){return value>=1000?Math.round(value).toLocaleString('en-IN'):value>=100?Math.round(value).toLocaleString('en-IN'):Number(value.toFixed(1)).toLocaleString('en-IN')}
function syncAllFibres(){
  const fibres=Object.keys(fibreMeta).map(name=>{const point=latestProductionPoint(name),meta=fibreMeta[name];if(!point)return null;const normalised=point.value*meta.factor,growth=point.previous&&point.previous!==0?(point.value-point.previous)/point.previous*100:null;return {name,meta,...point,normalised,growth}}).filter(Boolean);
  const comparable=fibres.filter(x=>!x.meta.separate),handloom=fibres.find(x=>x.meta.separate);
  if(!comparable.length)return;
  const total=comparable.reduce((sum,x)=>sum+x.normalised,0),leader=comparable.reduce((a,b)=>a.normalised>b.normalised?a:b),fastest=comparable.filter(x=>Number.isFinite(x.growth)).sort((a,b)=>b.growth-a.growth)[0]||leader;
  const displayNames={'Man-Made Fibres (MMF)':'MMF'};
  catalogue['All Fibres Overview']={
    kpis:[
      ['Comparable Fibre Output',formatAutoValue(total),'Mn Kg · auto-calculated'],
      ['Leading Fibre',displayNames[leader.name]||leader.name,formatAutoValue(leader.normalised)+' Mn Kg'],
      ['Fastest Growth',displayNames[fastest.name]||fastest.name,(fastest.growth>=0?'+':'')+(Number.isFinite(fastest.growth)?fastest.growth.toFixed(1):'–')+'% latest trend'],
      ['Handloom Output',handloom?formatAutoValue(handloom.value):'–',handloom?'Million metres · '+handloom.label:'Awaiting data']
    ],
    charts:[{
      type:'bar',
      title:'Comparable Fibre Production ('+(leader.label||'Latest')+') (Mn Kg)',
      labels:comparable.map(x=>displayNames[x.name]||x.name),
      series:[['Latest production',comparable.map(x=>Number(x.normalised.toFixed(2)))]],
      source:'Auto-calculated from the latest Cotton, Silk, Jute, Wool and MMF production charts. Original units are standardised to Mn Kg.'
    }],
    insights:[
      ['Live Fibre Summary','This overview updates automatically whenever any connected fibre chart is updated through the dashboard upload tool.'],
      ['Production Leader',(displayNames[leader.name]||leader.name)+' leads the comparable fibre mix with '+formatAutoValue(leader.normalised)+' Mn Kg in '+leader.label+'.'],
      ['Growth Signal',(displayNames[fastest.name]||fastest.name)+' shows the strongest latest available movement at '+(Number.isFinite(fastest.growth)?(fastest.growth>=0?'+':'')+fastest.growth.toFixed(1)+'%':'not available')+'.'],
      ['Unit Transparency','Cotton and jute are converted from bales; silk is converted from MT. Handloom remains separately reported in million metres.']
    ],
    autoGenerated:true
  };
}
function lineChart(c,area=false){const W=Math.max(1000,100+c.labels.length*105),H=350,p=60,raw=c.series[0]?.[1]||[],v=raw.map(x=>Number.isFinite(Number(x))?Number(x):0),scale=chartScale(v),span=Math.max(1,v.length-1),pts=v.map((n,i)=>[p+i*(W-p-25)/span,H-p-scale.project(n)*(H-2*p)]),ticks=[0,1,2,3,4],fillPath=pts.length?'M'+pts.map(x=>x.join(',')).join(' L')+' L'+pts.at(-1)[0]+','+(H-p)+' L'+p+','+(H-p)+'Z':'';return '<svg style="--chart-width:'+W+'px" viewBox="0 0 '+W+' '+H+'"><defs><linearGradient id="productionLineGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#00a395" stop-opacity=".28"/><stop offset="100%" stop-color="#00a395" stop-opacity=".02"/></linearGradient></defs>'+scaleLabel(scale,W)+'<g class="grid">'+ticks.map(i=>'<line x1="'+p+'" y1="'+(p+i*(H-2*p)/4)+'" x2="'+(W-25)+'" y2="'+(p+i*(H-2*p)/4)+'"/><text class="y-tick" x="'+(p-10)+'" y="'+(p+i*(H-2*p)/4+4)+'" text-anchor="end">'+fmt(scale.tick(i/4))+'</text>').join('')+'</g>'+(fillPath?'<path class="line-fill'+(area?' area-fill':'')+'" d="'+fillPath+'"/>':'')+'<polyline class="trend-line" points="'+pts.map(x=>x.join(',')).join(' ')+'"/>'+pts.map((x,i)=>'<circle cx="'+x[0]+'" cy="'+x[1]+'" r="5" data-tip="'+esc((c.series[0]?.[0]||'Value')+' · '+c.labels[i]+': '+v[i])+'"></circle><text x="'+x[0]+'" y="'+(H-14)+'" text-anchor="middle">'+esc(c.labels[i])+'</text>').join('')+'</svg>'}
function verticalChart(c){const seriesCount=Math.max(1,c.series.length),groupWidth=Math.max(88,seriesCount*14+24),W=Math.max(1000,85+c.labels.length*groupWidth),H=360,p=60,all=c.series.flatMap(x=>x[1]).map(Number).filter(Number.isFinite),scale=chartScale(all),g=(W-p-25)/Math.max(1,c.labels.length),bw=Math.max(7,Math.min(30,(g-22)/seriesCount)),ticks=[0,1,2,3,4];return '<svg style="--chart-width:'+W+'px" viewBox="0 0 '+W+' '+H+'">'+scaleLabel(scale,W)+'<g class="grid">'+ticks.map(i=>'<line x1="'+p+'" y1="'+(p+i*(H-2*p)/4)+'" x2="'+(W-25)+'" y2="'+(p+i*(H-2*p)/4)+'"/><text class="y-tick" x="'+(p-10)+'" y="'+(p+i*(H-2*p)/4+4)+'" text-anchor="end">'+fmt(scale.tick(i/4))+'</text>').join('')+'</g>'+c.labels.map((l,i)=>c.series.map((s,j)=>{const raw=Number(s[1][i]),n=Number.isFinite(raw)?raw:0,x=p+i*g+(g-seriesCount*bw)/2+j*bw,h=scale.pixels(n,H-2*p,5),y=H-p-h;return '<rect class="s'+j+'" x="'+x+'" y="'+y+'" width="'+Math.max(3,bw-3)+'" height="'+h+'" rx="4" data-tip="'+esc(s[0]+' · '+l+': '+n)+'"></rect>'}).join('')+'<text x="'+(p+i*g+g/2)+'" y="'+(H-14)+'" text-anchor="middle">'+esc(l)+'</text>').join('')+'</svg>'}
function stackedChart(c){const W=1000,H=380,left=105,right=30,plotW=W-left-right,totals=c.labels.map((_,i)=>c.series.reduce((a,s)=>a+Number(s[1][i]||0),0)),scale=chartScale(totals,1.08),row=(H-65)/c.labels.length,ticks=[0,1,2,3,4];return '<svg viewBox="0 0 '+W+' '+H+'">'+scaleLabel(scale,W)+ticks.map(i=>'<line class="stack-grid" x1="'+(left+i*plotW/4)+'" y1="5" x2="'+(left+i*plotW/4)+'" y2="'+(H-42)+'"/><text x="'+(left+i*plotW/4)+'" y="'+(H-15)+'" text-anchor="middle">'+fmt(scale.tick(1-i/4))+'</text>').join('')+c.labels.map((l,i)=>{let x=left,total=totals[i],totalW=scale.pixels(total,plotW,5);return '<text x="'+(left-10)+'" y="'+(i*row+row/2+5)+'" text-anchor="end">'+esc(l)+'</text>'+c.series.map((s,j)=>{const value=Number(s[1][i]||0),w=total>0?Math.max(value>0?2:0,totalW*value/total):0,out='<rect class="s'+j+'" x="'+x+'" y="'+(i*row+7)+'" width="'+w+'" height="'+(row-12)+'" data-tip="'+esc(s[0]+' · '+l+': '+value)+'"></rect>';x+=w;return out}).join('')}).join('')+'</svg>'}
const legend=s=>s.map((x,i)=>'<b><i class="s'+i+'"></i>'+esc(x[0])+'</b>').join('');
function chartHtml(c,i){const body=c.type==='line'?lineChart(c):c.type==='area'?lineChart(c,true):c.type==='stacked'?stackedChart(c):verticalChart(c);return '<article class="panel production-chart" data-chart-index="'+i+'"><div class="panel-head"><div><span class="overline">PRODUCTION ANALYTICS</span><h2>'+esc(c.title)+'</h2></div><button class="png-only">Export PNG</button></div><div class="svg-chart">'+body+'</div>'+(c.note?'<p class="chart-note">'+esc(c.note)+'</p>':'')+'<div class="chart-footer"><span class="dynamic-legend">'+legend(c.series)+'</span><em>Source: '+esc(c.source)+'</em></div></article>'}
function svgPng(panel,key){const svg=panel.querySelector('svg'),clone=svg.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='.grid line{stroke:#dce5e9;stroke-dasharray:4 5}text{fill:#536775;font:11px Arial}.area{fill:#dbc8d3}.line-fill{fill:url(#productionLineGradient);opacity:.7}.trend-line{fill:none;stroke:#711044;stroke-width:4}.s0{fill:#711044}.s1{fill:#9b1b67}.s2{fill:#26ae69}.s3{fill:#e16b44}.s4{fill:#7564a4}.s5{fill:#c95c9e}.s6{fill:#3484c6}.s7{fill:#ef6f61}.s8{fill:#7b9d36}.s9{fill:#8a5bb5}circle{fill:white;stroke:#711044;stroke-width:4}';clone.prepend(style);const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'})),img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=2000;canvas.height=700;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,2000,700);ctx.drawImage(img,0,0,2000,700);const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='production-'+key.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.png';a.click();URL.revokeObjectURL(url);if(window.notify)window.notify('Chart PNG downloaded')};img.src=url}
function bindHover(panel){const tip=document.createElement('div');tip.className='chart-hover-tip';panel.appendChild(tip);panel.querySelectorAll('[data-tip]').forEach(mark=>{mark.addEventListener('mouseenter',()=>{tip.textContent=mark.dataset.tip;tip.classList.add('show');mark.classList.add('mark-hover')});mark.addEventListener('mousemove',e=>{const r=panel.getBoundingClientRect();tip.style.left=(e.clientX-r.left+12)+'px';tip.style.top=(e.clientY-r.top-38)+'px'});mark.addEventListener('mouseleave',()=>{tip.classList.remove('show');mark.classList.remove('mark-hover')})})}
function render(){syncAllFibres();const key=select.value,d=catalogue[key];if(!d)return;root.querySelector('.production-badge').textContent=d.autoGenerated?'Auto-synced from fibre data':'Illustrative data';renderVisual(key);kpiHost.innerHTML=(d.kpis||[]).map((x,i)=>'<article><span>'+icons[i%icons.length]+'</span><p>'+esc(x[0])+'</p><b>'+esc(x[1])+'</b><small>'+esc(x[2]||'')+'</small></article>').join('');chartHost.innerHTML=(d.charts||[]).map(chartHtml).join('');insightHost.innerHTML=(d.insights||[]).map((x,i)=>'<article><span>'+['◎','↗','◇','⌖','✓','▤'][i%6]+'</span><div><h3>'+esc(x[0])+'</h3><p>'+esc(x[1])+'</p></div></article>').join('');chartHost.querySelectorAll('.production-chart').forEach((p,i)=>{p.querySelector('.png-only').onclick=()=>svgPng(p,key+'-'+(i+1));bindHover(p)})}
function refreshOptions(preferred){syncAllFibres();select.innerHTML=Object.keys(catalogue).map(x=>'<option>'+esc(x)+'</option>').join('');if(preferred&&catalogue[preferred])select.value=preferred;render()}
window.productionDashboard={getData:()=>{syncAllFibres();return JSON.parse(JSON.stringify(catalogue))},getCategory:name=>{syncAllFibres();return JSON.parse(JSON.stringify(catalogue[name]||null))},updateCategory:(name,payload)=>{catalogue[name]=payload;syncAllFibres();localStorage.setItem(productionStorageKey,JSON.stringify(catalogue));refreshOptions(name)},importAll:payload=>{if(!payload||typeof payload!=='object')throw new Error('Invalid production data');Object.keys(catalogue).forEach(k=>delete catalogue[k]);Object.assign(catalogue,payload);syncAllFibres();localStorage.setItem(productionStorageKey,JSON.stringify(catalogue));refreshOptions(Object.keys(catalogue)[0])},reset:()=>{Object.keys(catalogue).forEach(k=>delete catalogue[k]);Object.assign(catalogue,JSON.parse(JSON.stringify(defaultCatalogue)));localStorage.removeItem(productionStorageKey);refreshOptions('All Fibres Overview')},render};
select.onchange=render;render();loadPublishedData();
})();
