(function(){
const api=window.productionDashboard,nav=document.getElementById('moduleNav');if(!api||!nav)return;
const button=document.createElement('button');button.className='upload-nav-button';button.innerHTML='<i>⇧</i><span>Upload Data</span><em></em>';nav.appendChild(button);
const modal=document.createElement('div');modal.className='data-modal';modal.innerHTML='<section class="data-workbench"><header class="workbench-head"><div><p>DATA ADMINISTRATION</p><h2>Upload & Update Dashboard Data</h2></div><button class="modal-close" aria-label="Close">×</button></header><div class="workbench-body"><div class="import-steps"><span class="active"><i>1</i>Select file</span><span><i>2</i>Preview</span><span><i>3</i>Map data</span><span><i>4</i>Apply</span></div><label class="upload-drop" id="dataDrop"><span>⇧</span><h3>Drop your data file here</h3><p>Excel, CSV, JSON, PDF and DOCX supported</p><b>Choose file</b><input id="dataFile" type="file" accept=".xlsx,.xls,.csv,.json,.pdf,.docx"></label><div class="file-summary" id="fileSummary"><div><b id="fileName"></b><small id="fileMeta"></small></div><span class="file-status" id="fileStatus">Ready</span></div><div class="mapping-grid" id="mappingGrid"><div class="map-field"><label>Update section</label><select id="importMode"><option value="chart">Chart data</option><option value="kpis">KPI cards</option><option value="insights">Insight cards</option><option value="full">Complete JSON backup</option></select></div><div class="map-field"><label>Fibre category</label><select id="targetFibre"></select></div><div class="map-field chart-map"><label>Existing chart</label><select id="targetChart"></select></div><div class="map-field"><label>Label / title column</label><select id="labelColumn"></select></div><div class="map-field wide"><label>Value columns (Ctrl + click for multiple)</label><select id="valueColumns" multiple></select></div><div class="map-field chart-map"><label>Chart type</label><select id="chartType"><option value="line">Line</option><option value="bar">Bar</option><option value="grouped">Grouped bars</option><option value="area">Area</option><option value="stacked">Stacked horizontal</option></select></div><div class="map-field wide chart-map"><label>Chart title</label><input id="chartTitle" placeholder="Production chart title"></div><div class="map-field chart-map"><label>Source</label><input id="chartSource" placeholder="Official data source"></div></div><div class="preview-card" id="previewCard"><div class="preview-head"><b>Data preview</b><span id="previewCount"></span></div><div class="preview-scroll" id="previewScroll"></div></div><div class="import-log" id="importLog"></div><div class="import-actions"><div class="action-group"><button class="work-btn" id="downloadBackup">Download JSON Backup</button><button class="work-btn" id="downloadTemplate">Download CSV Template</button><button class="work-btn danger" id="resetData">Reset Dummy Data</button></div><div class="action-group"><button class="work-btn" id="clearImport">Clear</button><button class="work-btn primary" id="applyImport" disabled>Apply to Dashboard</button></div></div></div></section>';document.body.appendChild(modal);
const $=id=>document.getElementById(id),drop=$('dataDrop'),fileInput=$('dataFile'),summary=$('fileSummary'),mapping=$('mappingGrid'),preview=$('previewCard'),log=$('importLog'),apply=$('applyImport');let rows=[],columns=[],jsonPayload=null;
function open(){modal.classList.add('open');refreshFibres()}function close(){modal.classList.remove('open')}button.onclick=open;document.querySelector('.topbar .data-button').onclick=open;modal.querySelector('.modal-close').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close()});
function say(message,error=false){log.textContent=message;log.className='import-log show'+(error?' error':'')}
function refreshFibres(){const names=Object.keys(api.getData());$('targetFibre').innerHTML=names.map(x=>'<option>'+x+'</option>').join('');refreshCharts()}
function refreshCharts(){const d=api.getCategory($('targetFibre').value),charts=d?.charts||[];$('targetChart').innerHTML=charts.map((x,i)=>'<option value="'+i+'">'+x.title+'</option>').join('')+'<option value="new">+ Add new chart</option>';const c=charts[0];if(c){$('chartTitle').value=c.title;$('chartSource').value=c.source;$('chartType').value=c.type}}
function parseCsv(text){const out=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&quote&&next==='"'){cell+='"';i++}else if(ch==='"')quote=!quote;else if(ch===','&&!quote){row.push(cell.trim());cell=''}else if((ch==='\n'||ch==='\r')&&!quote){if(ch==='\r'&&next==='\n')i++;row.push(cell.trim());if(row.some(Boolean))out.push(row);row=[];cell=''}else cell+=ch}row.push(cell.trim());if(row.some(Boolean))out.push(row);return arraysToObjects(out)}
function arraysToObjects(matrix){if(!matrix.length)return[];const headers=matrix[0].map((x,i)=>String(x||'Column '+(i+1)).trim());return matrix.slice(1).filter(r=>r.some(x=>String(x).trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}
function normalizedSheetRows(matrix){const source=matrix.map(row=>row.map(v=>String(v??'').replace(/\s+/g,' ').trim()));while(source.length&&source[source.length-1].every(x=>!x))source.pop();if(!source.length)return[];const width=Math.max(...source.map(r=>r.length)),fixed=source.map(r=>Array.from({length:width},(_,i)=>r[i]||''));let dataStart=1;for(let i=0;i<Math.min(fixed.length,12);i++){const populated=fixed[i].filter(Boolean).length,numeric=fixed[i].filter(v=>v!==''&&Number.isFinite(Number(String(v).replace(/,/g,'')))).length;if(numeric>=2&&populated>=3){dataStart=i;break}}const headerRows=fixed.slice(0,dataStart),headers=[];for(let col=0;col<width;col++){const parts=[];let carry='';headerRows.forEach(row=>{let value=row[col];if(value)carry=value;else value=carry;if(value&&!parts.includes(value))parts.push(value)});headers.push(parts.join(' – ')||'Column '+(col+1))}const data=fixed.slice(dataStart).filter(r=>r.some(Boolean)),keep=headers.map((h,i)=>({h,i})).filter(({h,i})=>!/^Column \d+$/.test(h)||data.some(r=>String(r[i]??'').trim())),seen={},unique=keep.map(({h})=>{seen[h]=(seen[h]||0)+1;return seen[h]>1?h+' ('+seen[h]+')':h});return data.map(row=>Object.fromEntries(keep.map(({i},idx)=>[unique[idx],row[i]??''])))}
function textRows(text){const matrix=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(x=>x.split(/\t|\s{2,}/).map(v=>v.trim()));return arraysToObjects(matrix)}
async function parsePdf(buffer){if(!window.pdfjsLib)throw new Error('PDF parser could not load. Check internet connection.');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await pdfjsLib.getDocument({data:buffer}).promise,matrix=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent(),lines={};content.items.forEach(item=>{const y=Math.round(item.transform[5]/3)*3;(lines[y]||(lines[y]=[])).push({x:item.transform[4],text:item.str})});Object.keys(lines).sort((a,b)=>b-a).forEach(y=>matrix.push(lines[y].sort((a,b)=>a.x-b.x).map(x=>x.text.trim()).filter(Boolean)))}return arraysToObjects(matrix)}
async function parseFile(file){const ext=file.name.split('.').pop().toLowerCase(),buffer=await file.arrayBuffer();jsonPayload=null;if(ext==='json'){jsonPayload=JSON.parse(new TextDecoder().decode(buffer));const payload=jsonPayload.production||jsonPayload;rows=Object.keys(payload).map(k=>({Category:k,Charts:(payload[k].charts||[]).length,KPIs:(payload[k].kpis||[]).length,Insights:(payload[k].insights||[]).length}));return}if(ext==='csv'){rows=parseCsv(new TextDecoder().decode(buffer));return}if(ext==='xlsx'||ext==='xls'){if(!window.XLSX)throw new Error('Excel parser could not load. Check internet connection.');const wb=XLSX.read(buffer,{type:'array'}),sheet=wb.Sheets[wb.SheetNames[0]],matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',blankrows:false});rows=normalizedSheetRows(matrix);return}if(ext==='docx'){if(!window.mammoth)throw new Error('DOCX parser could not load. Check internet connection.');const result=await mammoth.extractRawText({arrayBuffer:buffer});rows=textRows(result.value);return}if(ext==='pdf'){rows=await parsePdf(buffer);return}throw new Error('Unsupported file format')}
function fillMapping(){columns=rows.length?Object.keys(rows[0]):[];const opts=columns.map(x=>'<option value="'+x+'">'+x+'</option>').join('');$('labelColumn').innerHTML=opts;$('valueColumns').innerHTML=opts;const numeric=columns.filter(c=>rows.some(r=>Number.isFinite(Number(String(r[c]).replace(/,/g,'')))));const likelyLabel=columns.find(c=>/state|district|region|year|period|category|product/i.test(c))||columns.find(c=>!numeric.includes(c))||columns[0];$('labelColumn').value=likelyLabel;const likelyValues=numeric.filter(c=>/production|output|quantity|value|202\d|20\d\d/i.test(c));[...$('valueColumns').options].forEach(o=>o.selected=(likelyValues.length?likelyValues:numeric).includes(o.value));mapping.classList.add('show');apply.disabled=!columns.length&&$('importMode').value!=='full'}
function showPreview(){const view=rows.slice(0,20),cols=view.length?Object.keys(view[0]):[];$('previewCount').textContent=rows.length+' rows · '+cols.length+' columns';$('previewScroll').innerHTML='<table><thead><tr>'+cols.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+view.map(r=>'<tr>'+cols.map(c=>'<td>'+String(r[c]??'')+'</td>').join('')+'</tr>').join('')+'</tbody></table>';preview.classList.add('show')}
async function load(file){if(!file)return;$('fileName').textContent=file.name;$('fileMeta').textContent=(file.size/1024).toFixed(1)+' KB';$('fileStatus').textContent='Parsing…';summary.classList.add('show');say('Reading and validating the uploaded file…');try{await parseFile(file);$('fileStatus').textContent='Parsed';showPreview();fillMapping();if(jsonPayload)$('importMode').value='full';toggleMode();say('File parsed successfully. Review the preview and mapping before applying.')}catch(error){$('fileStatus').textContent='Error';say(error.message,true);apply.disabled=true}}
fileInput.onchange=e=>load(e.target.files[0]);['dragenter','dragover'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>load(e.dataTransfer.files[0]));
$('targetFibre').onchange=refreshCharts;$('targetChart').onchange=()=>{const d=api.getCategory($('targetFibre').value),c=d?.charts?.[Number($('targetChart').value)];if(c){$('chartTitle').value=c.title;$('chartSource').value=c.source;$('chartType').value=c.type}};
function toggleMode(){const chart=$('importMode').value==='chart';modal.querySelectorAll('.chart-map').forEach(x=>x.style.display=chart?'grid':'none');apply.disabled=$('importMode').value==='full'?!jsonPayload:!rows.length}$('importMode').onchange=toggleMode;
const num=v=>{const n=Number(String(v??'').replace(/,/g,'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:0};
apply.onclick=()=>{try{const mode=$('importMode').value;if(mode==='full'){const payload=jsonPayload?.production||jsonPayload;if(!payload)throw new Error('Upload a valid dashboard JSON backup first.');api.importAll(payload);say('Complete production dataset imported and saved in this browser.');return}const fibre=$('targetFibre').value,d=api.getCategory(fibre),label=$('labelColumn').value,values=[...$('valueColumns').selectedOptions].map(x=>x.value);if(!label||!values.length)throw new Error('Select one label column and at least one value column.');if(mode==='chart'){const chart={type:$('chartType').value,title:$('chartTitle').value||'Production Chart',labels:rows.map(r=>String(r[label])),series:values.map(c=>[c,rows.map(r=>num(r[c]))]),source:$('chartSource').value||'Uploaded data'};const index=$('targetChart').value;if(index==='new')d.charts.push(chart);else d.charts[Number(index)]=chart}else if(mode==='kpis')d.kpis=rows.slice(0,4).map(r=>[String(r[label]),String(r[values[0]]??''),String(r[values[1]]??'')]);else d.insights=rows.map(r=>[String(r[label]),String(r[values[0]]??'')]);api.updateCategory(fibre,d);say(fibre+' '+mode+' updated successfully. Data is saved locally and visible on the Production dashboard.');refreshCharts()}catch(error){say(error.message,true)}};
$('downloadBackup').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({production:api.getData()},null,2)],{type:'application/json'}));a.download='textile-dashboard-production-backup.json';a.click()};
$('downloadTemplate').onclick=()=>{const csv='Year,Series A,Series B\n2022-23,100,75\n2023-24,120,82\n2024-25,135,91';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='production-chart-template.csv';a.click()};
$('resetData').onclick=()=>{if(confirm('Reset all imported Production data and restore dummy data?')){api.reset();refreshFibres();say('Dummy Production data restored.')}};$('clearImport').onclick=()=>{rows=[];columns=[];jsonPayload=null;fileInput.value='';summary.classList.remove('show');mapping.classList.remove('show');preview.classList.remove('show');log.className='import-log';apply.disabled=true};
})();
