(function(){
const opts={production:['All Fibres Overview','Cotton','Silk','Jute','Wool','Man-Made Fibres (MMF)','Handloom'],domestic:['Households vs Exports vs Non-Households','Fibre-wise','Major Varieties','Gender-wise','Income-wise','Region-wise','Sector of manufacture','Value added','Technical textile'],trade:['Export','Import']};
const toast=m=>window.notify?window.notify(m):alert(m);
function bar(root,label,items){if(!root||root.querySelector('.module-filter-bar'))return;const b=document.createElement('div');b.className='module-filter-bar';b.innerHTML=`<span>⌕</span><label>${label}</label><select>${items.map(x=>`<option>${x}</option>`).join('')}</select><em>Dummy data · filter-ready</em>`;root.prepend(b);b.querySelector('select').onchange=e=>{toast(`${label}: ${e.target.value}`);if(label==='Fibre category'){const h=root.querySelector('h2');if(h)h.textContent=`${e.target.value} Production Trends (MT)`;}};}
bar(document.getElementById('domesticDashboard'),'Market view',opts.domestic);bar(document.getElementById('tradeDashboard'),'Trade type',opts.trade);
function csv(p,n){const rows=[['Chart',p.querySelector('h2')?.textContent||n],['Selected filters',[...p.querySelectorAll('select')].map(s=>s.value).join(' | ')||'All']];p.querySelectorAll('table tr').forEach(tr=>rows.push([...tr.querySelectorAll('th,td')].map(x=>x.textContent.trim())));if(rows.length===2)rows.push(['Status','Illustrative demo data']);const out=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'text/csv'}));a.download=`${n}.csv`;a.click();toast('Selected chart CSV downloaded');}
async function png(p,n){if(!window.html2canvas)return toast('PNG export ke liye internet connection check karein');const c=await html2canvas(p,{backgroundColor:'#fff',scale:2});const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download=`${n}.png`;a.click();toast('Selected chart PNG downloaded');}
function pdf(p){document.body.classList.add('print-chart-only');p.classList.add('print-target');window.print();setTimeout(()=>{document.body.classList.remove('print-chart-only');p.classList.remove('print-target')},500);toast('Selected chart PDF print dialog opened');}
document.querySelectorAll('#domesticDashboard .panel,#tradeDashboard .panel').forEach(p=>{const h=p.querySelector('.panel-head');if(!h)return;const b=document.createElement('div');b.className='chart-toolbar';const n=(p.querySelector('h2')?.textContent||'chart').replace(/[^a-z0-9]+/gi,'-').toLowerCase();b.innerHTML='<span>Chart tools</span><button>Export PNG</button><button>Export CSV</button><button>Export PDF</button>';h.appendChild(b);b.children[1].onclick=()=>png(p,n);b.children[2].onclick=()=>csv(p,n);b.children[3].onclick=()=>pdf(p);});
})();
